# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dq0MY95jcjBwHdrvUbIwkNcJq6Vfj-Z7
"""

# 단어의 개수
A = "The Curious Case of Benjamin Button"
B = " The Curious Case of Benjamin Button"
C = "The Curious Case of Benjamin Button "

Alist = list(A.split())
Blist = list(B.split())
Clist = list(C.split())

print(Alist, len(Alist))
print(Blist, len(Blist))
print(Clist, len(Clist))