# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dq0MY95jcjBwHdrvUbIwkNcJq6Vfj-Z7
"""

# 숫자 세기
answer = 1
for _ in range(3):
    answer*=int(input())
for i in range(10):
    print(str(answer).count(str(i)))