# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gMwL7jQrZAILwVbr8r0dP1QeC7WfBjn
"""

N, M = map(int,input().split())
print((N*M)-1)
"""
1 * 1 = 0
2 * 1 = 1
3 * 1 = 2

1 * 2 = 1
2 * 2 = 3
3 * 2 = 5

1 * 3 = 2
2 * 3 = 5
3 * 3 = 8

"""