# -*- coding: utf-8 -*-
"""문제풀이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sx-fwPsrot0eVVRbm8oaSNr3EV5BmvwW
"""

print("\    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \(__)|")