# -*- coding: utf-8 -*-
"""문제풀이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sx-fwPsrot0eVVRbm8oaSNr3EV5BmvwW
"""

A, B = map(int, input().split())
if A > B:
    print(">")
elif A < B:
    print("<")
else:
    print("==")