# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FNEIk26RWJUTivENsReMc_TnfbZfp4fW
"""

y = int(input())

answer = y-543
print(answer)