# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmFVMkxr__Y0gjPa64Ks0rQ7uZ56tj3Y
"""

T = int(input())
P = ""
for _ in range(T):
  R, S = input().split()
  R = int(R)
  for a in S:
    P+=a*R
  print(P)
  P=""