# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gMwL7jQrZAILwVbr8r0dP1QeC7WfBjn
"""

from datetime import datetime

datetime.now()

today = datetime.today()

print("{}-{}-{}".format(today.year,today.month,today.day))

