# -*- coding: utf-8 -*-
"""문제풀이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sx-fwPsrot0eVVRbm8oaSNr3EV5BmvwW
"""

# 고양이
print("\    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \(__)|")

# 개
print("|\_/|")
print("|q p|   /}")
print("( 0 )\"\"\"\\")
print("|\"^\"`    |")
print("||_/=\\\\__|")

# 새싹
print("         ,r'\"7")
print("r`-_   ,'  ,/")
print(" \. \". L_r'")
print("   `~\/")
print("      |")
print("      |")