# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CxsMhlXt-89lQsl8GWv7YVm_oSJtNMwo
"""



T = int(input())

for i in range(1,T+1):
    A, B = map(int, input().split())
    print("Case #{}: {}".format(i, A+B))