# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gMwL7jQrZAILwVbr8r0dP1QeC7WfBjn
"""

R1, S = map(int,input().split())
R2 = 2*S-R1
print(R2)