# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dq0MY95jcjBwHdrvUbIwkNcJq6Vfj-Z7
"""

# 사분면 고르기
x = int(input())
y = int(input())

if x > 0 and y > 0:
    print(1)
elif x < 0 and y < 0:
    print(3)
else:
    if x < 0:
        print(2)
    else:
        print(4)